# -*- coding: utf-8 -*-
"""Chat_BOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RriDPLG9r42nP0kgSKx2X51Xh1xTuJRZ
"""

!pip install google-genai

import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

from google import genai

client = genai.Client()

for model in client.models.list():
  print(model.name)

modelo = "gemini-2.0-flash"

resposta = client.models.generate_content(model=modelo, contents="Quem é a empresa por trás dos modelos Gemini?")

resposta.text

chat = client.chats.create(model=modelo)

resposta = chat.send_message("Oi tudo bem?")

resposta.text

resposta = chat.send_message("O que é inteligência artificial?")

resposta.text

resposta = chat.send_message("Você é um assistente pessoal e você sempre responde de forma sucinta. O que é inteligência artificial?")

resposta.text

from google.genai import types

chat_config = types.GenerateContentConfig(
    system_instruction="Você é um assistente pessoal e você sempre responde de forma sucinta. Tentar limitar em até 200 caracteres",
)

chat = client.chats.create(model=modelo, config=chat_config)

resposta = chat.send_message("O que computação quantica?")

resposta.text









chat.get_history()

prompt = input("Esperando o prompt: ")

while prompt != "fim":
  resposta = chat.send_message(prompt)
  print("Resposta: ", resposta.text)
  print("\n\n")
  prompt = input("Esperando o prompt: ")

chat.get_history()

chat_config_2 = types.GenerateContentConfig(
    system_instruction="Você é um assistente pessoal que sempre responde de forma sarcástica.",
)

chat_2 = client.chats.create(model=modelo, config=chat_config_2)

resposta = chat_2.send_message("O que computação quantica?")

resposta.text